import { type NextPage } from "next";
import Head from "next/head";
import { api } from "../utils/api";

// external imports
import { FaGithub } from "react-icons/fa";

type Inputs = {
  bio: string;
  vibe: string;
  platform: string;
};

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Bio Generator</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container mx-auto mt-32 flex min-h-screen max-w-2xl flex-col gap-5">
        <a
          aria-label="navigate to github repository"
          href="https://github.com/sadmann7/biogen"
          target="_blank"
          rel="noreferrer"
          className="mx-auto flex w-fit items-center gap-1 rounded-full bg-white px-3 py-1 font-medium transition-colors hover:bg-gray-200 active:bg-gray-100"
        >
          <FaGithub className="mr-1 inline-block" size={18} />
          <span>Star on GitHub</span>
        </a>
        <div className="grid gap-5">
          <h1 className="text-center text-3xl font-bold tracking-wide text-white sm:text-5xl">
            Generate your social media bios with AI
          </h1>
          <span className="text-center text-base text-gray-300 sm:text-lg">
            69 Bios generated so far
          </span>
        </div>
      </main>
    </>
  );
};

export default Home;
